
CREATE TABLE PRICES (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    BRAND_ID INT,
    START_DATE VARCHAR(19),
    END_DATE VARCHAR(19),
    PRICE_LIST INT,
    PRODUCT_ID INT,
    PRIORITY INT,
    PRICE FLOAT,
    CURR VARCHAR(3)
);