
CREATE TABLE PRICES (
    BRAND_ID INT,
    START_DATE VARCHAR(19),
    END_DATE VARCHAR(19),
    PRICE_LIST INT PRIMARY KEY,
    PRODUCT_ID INT,
    PRIORITY INT,
    PRICE FLOAT,
    CURR VARCHAR(3)
);